
enum {
        MEDUSA_EVENT_IN         = 0x00000001,
        MEDUSA_EVENT_OUT        = 0x00000002,
        MEDUSA_EVENT_PRI        = 0x00000004,
        MEDUSA_EVENT_ERR        = 0x00000008,
        MEDUSA_EVENT_HUP        = 0x00000010,
        MEDUSA_EVENT_NVAL       = 0x00000020,

        MEDUSA_EVENT_TIMEOUT    = 0x01000000,

#define MEDUSA_EVENT_IN         MEDUSA_EVENT_IN
#define MEDUSA_EVENT_OUT        MEDUSA_EVENT_OUT
#define MEDUSA_EVENT_PRI        MEDUSA_EVENT_PRI
#define MEDUSA_EVENT_ERR        MEDUSA_EVENT_ERR
#define MEDUSA_EVENT_HUP        MEDUSA_EVENT_HUP
#define MEDUSA_EVENT_NVAL       MEDUSA_EVENT_NVAL
#define MEDUSA_EVENT_TIMEOUT    MEDUSA_EVENT_TIMEOUT
};
