
enum {
        MEDUSA_SUBJECT_FLAG_NONE        = 0x00000000,
        MEDUSA_SUBJECT_FLAG_ALLOC       = 0x00000001,
        MEDUSA_SUBJECT_FLAG_IO          = 0x00000100,
        MEDUSA_SUBJECT_FLAG_TIMER       = 0x00000200,
        MEDUSA_SUBJECT_FLAG_MOD         = 0x00010000,
        MEDUSA_SUBJECT_FLAG_DEL         = 0x00020000,
        MEDUSA_SUBJECT_FLAG_ROGUE       = 0x00040000,
        MEDUSA_SUBJECT_FLAG_POLL        = 0x01000000,
        MEDUSA_SUBJECT_FLAG_HEAP        = 0x02000000
#define MEDUSA_SUBJECT_FLAG_NONE        MEDUSA_SUBJECT_FLAG_NONE
#define MEDUSA_SUBJECT_FLAG_ALLOC       MEDUSA_SUBJECT_FLAG_ALLOC
#define MEDUSA_SUBJECT_FLAG_IO          MEDUSA_SUBJECT_FLAG_IO
#define MEDUSA_SUBJECT_FLAG_TIMER       MEDUSA_SUBJECT_FLAG_TIMER
#define MEDUSA_SUBJECT_FLAG_NONE        MEDUSA_SUBJECT_FLAG_NONE
#define MEDUSA_SUBJECT_FLAG_MOD         MEDUSA_SUBJECT_FLAG_MOD
#define MEDUSA_SUBJECT_FLAG_DEL         MEDUSA_SUBJECT_FLAG_DEL
#define MEDUSA_SUBJECT_FLAG_ROGUE       MEDUSA_SUBJECT_FLAG_ROGUE
#define MEDUSA_SUBJECT_FLAG_POLL        MEDUSA_SUBJECT_FLAG_POLL
#define MEDUSA_SUBJECT_FLAG_HEAP        MEDUSA_SUBJECT_FLAG_HEAP
};

TAILQ_HEAD(medusa_subjects, medusa_subject);
struct medusa_subject {
        TAILQ_ENTRY(medusa_subject) subjects;
        unsigned int flags;
        struct medusa_monitor *monitor;
};
